version: "2"
services:

 hotrod:
   image: jaegertracing/example-hotrod:latest
   ports:
     - "8080:8080"
   command: ["all"]
   environment:
     - JAEGER_AGENT_HOST=collector
     - JAEGER_AGENT_PORT=6831

 collector:
   image: otel/opentelemetry-collector:0.23.0
   command: "--config /etc/otel-config.yaml"
   volumes:
     - ./otel-config.yaml:/etc/otel-config.yaml
