receivers:
 jaeger:
   protocols:
     thrift_compact:

processors:
 batch:

exporters:
 otlp:
   endpoint: tempo-eu-west-0.grafana.net:443
   headers:
     authorization: eyJrIjoiNGRkNmFkNzViNWZiMWU1N2MxODJkYmYwNjZhZjkxYTI5YzM3OTJiNiIsIm4iOiJNeUFwaSIsImlkIjo2ODA3NjJ9

service:
 pipelines:
   traces:
     receivers: [jaeger]
     processors: [batch]
     exporters: [otlp]
