server:
  http_listen_port: 4317
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://251884:eyJrIjoiYzFjMDMzYmFjNjA0ODNhZGJiNTVmYWQxZTk3Y2FiYTIzYTI0MjljNiIsIm4iOiJMb2tpQXBpS2V5IiwiaWQiOjY4MDc2Mn0=@logs-prod-eu-west-0.grafana.net/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log